version: "3.5"

services:
  nginx:
    image: nginx:alpine
    container_name: supster-nginx
    working_dir: /application
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../:/application
    ports:
      - '80:80'
    depends_on:
      - php-fpm

  postgres:
    image: postgres:12.6
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: someuser
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - '5432:5432'

  php-fpm:
    build: php
    container_name: supster-php-fpm
    working_dir: /application
    volumes:
      - ../:/application
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini

    ports:
      - '9000'
    links:
      - postgres

  phppgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres

  portainer:
    image: portainer/portainer
    command: --admin-password '123456'
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672

